name: Hourly Dataset Update

on:
  schedule:
    # Run every hour
    - cron: "0 * * * *"
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      slug:
        description: "Dataset slug to update (overrides default)"
        required: false
        default: ""

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          uv sync

      - name: Set POLIS_DATASET_SLUG
        run: |
          if [ -n "${{ github.event.inputs.slug }}" ]; then
            echo "POLIS_DATASET_SLUG=${{ github.event.inputs.slug }}" >> $GITHUB_ENV
          else
            echo "POLIS_DATASET_SLUG=${{ env.POLIS_DATASET_SLUG }}" >> $GITHUB_ENV
          fi

      - name: Update dataset
        run: |
          echo "Updating dataset: $POLIS_DATASET_SLUG"
          uv run python generate.py

      - name: Check for last_vote changes in meta.json
        run: |
          # Get all changed files
          CHANGED_FILES=$(git diff --name-only)

          # Get all dataset directories with changes
          DATASET_DIRS=$(echo "$CHANGED_FILES" | grep "data/datasets/" | cut -d'/' -f1-3 | sort | uniq)

          # Flag to track if any last_vote fields have changed
          LAST_VOTE_CHANGED=false

          # Process each dataset directory
          for DIR in $DATASET_DIRS; do
            # Check if meta.json exists in this directory
            if [ -f "$DIR/meta.json" ]; then
              # Check if the last_vote field has changed in meta.json
              if git diff -U0 "$DIR/meta.json" | grep -q '^\+.*"last_vote":'; then
                echo "Directory $DIR has last_vote changes in meta.json - keeping all changes"
                LAST_VOTE_CHANGED=true
              else
                echo "Directory $DIR has no last_vote changes - reverting entire directory"
                git checkout -- "$DIR"
              fi
            else
              # If meta.json doesn't exist, this might be a new dataset
              if echo "$CHANGED_FILES" | grep -q "^$DIR/meta.json$"; then
                echo "Directory $DIR has a new meta.json file - keeping all changes"
                LAST_VOTE_CHANGED=true
              else
                echo "Directory $DIR has no meta.json - reverting entire directory"
                git checkout -- "$DIR"
              fi
            fi
          done

          # Also check if datasets.json has changed
          if echo "$CHANGED_FILES" | grep -q "data/datasets.json"; then
            echo "datasets.json has changed - keeping this change"
            LAST_VOTE_CHANGED=true
          fi

          # Check if we still have any changes to commit
          if [ "$LAST_VOTE_CHANGED" = "false" ]; then
            echo "No last_vote changes detected - nothing to commit"
            exit 0
          else
            echo "Last vote changes detected - proceeding with commit"
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update dataset: ${{ env.POLIS_DATASET_SLUG }} - new votes detected [skip ci]"
          file_pattern: "data/**/*"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions <github-actions[bot]@users.noreply.github.com>"
          skip_dirty_check: false # Only commit if there are changes
