name: Hourly Dataset Update

on:
  schedule:
    # Run every hour
    - cron: "0 * * * *"
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      slug:
        description: "Dataset slug to update (overrides default)"
        required: false
        default: ""

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python and uv
        uses: astral-sh/setup-uv-action@v1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          uv sync

      - name: Update dataset
        env:
          # Set the default slug to update - change this to your preferred dataset
          POLIS_DATASET_SLUG: ${{ github.event.inputs.slug || 'jean-lou' }}
        run: |
          echo "Updating dataset: $POLIS_DATASET_SLUG"
          uv run python generate.py

      - name: Selectively revert votes.db changes
        run: |
          # Get all changed files
          CHANGED_FILES=$(git diff --name-only)

          # Get all dataset directories with changes
          DATASET_DIRS=$(echo "$CHANGED_FILES" | grep "data/datasets/" | cut -d'/' -f1-3 | sort | uniq)

          # Process each dataset directory
          for DIR in $DATASET_DIRS; do
            # Check if any non-votes.db files have changed in this directory
            if echo "$CHANGED_FILES" | grep "^$DIR/" | grep -v "votes\.db$" | grep -q .; then
              echo "Directory $DIR has non-votes.db changes - keeping all changes"
            else
              echo "Directory $DIR only has votes.db changes - reverting entire directory"
              git checkout -- "$DIR"
            fi
          done

          # Check if we still have any changes to commit
          if git diff --quiet; then
            echo "No significant changes to commit after reverting votes.db-only directories"
            exit 0
          else
            echo "Significant changes remain - proceeding with commit"
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update dataset: ${{ env.POLIS_DATASET_SLUG }} [skip ci]"
          file_pattern: "data/**/*"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions <github-actions[bot]@users.noreply.github.com>"
          skip_dirty_check: false # Only commit if there are changes
          # Ignore whitespace changes to reduce noise from formatting differences
          commit_options: "--no-verify --signoff --ignore-space-change"
